"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

from zav.user_documents_connector.api_client import ApiClient, Endpoint as _Endpoint
from zav.user_documents_connector.model_utils import (  # noqa: F401
    check_allowed_values,
    check_validations,
    date,
    datetime,
    file_type,
    none_type,
    validate_and_convert_types
)
from zav.user_documents_connector.model.error_response import ErrorResponse
from zav.user_documents_connector.model.http_validation_error import HTTPValidationError
from zav.user_documents_connector.model.paginated_response_user_document_item import PaginatedResponseUserDocumentItem
from zav.user_documents_connector.model.user_document_form import UserDocumentForm
from zav.user_documents_connector.model.user_document_item import UserDocumentItem


class ExternalDocumentsApi(object):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client
        self.create_external_document_endpoint = _Endpoint(
            settings={
                'response_type': (UserDocumentItem,),
                'auth': [],
                'endpoint_path': '/external-documents',
                'operation_id': 'create_external_document',
                'http_method': 'POST',
                'servers': None,
            },
            params_map={
                'all': [
                    'tenant',
                    'user_tenants',
                    'requester_uuid',
                    'user_roles',
                    'user_document_form',
                    'use_openai',
                    'index_id',
                ],
                'required': [
                    'tenant',
                    'user_tenants',
                    'requester_uuid',
                    'user_roles',
                    'user_document_form',
                ],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'tenant':
                        (str,),
                    'user_tenants':
                        (str,),
                    'requester_uuid':
                        (str,),
                    'user_roles':
                        (str,),
                    'user_document_form':
                        (UserDocumentForm,),
                    'use_openai':
                        (bool,),
                    'index_id':
                        (str,),
                },
                'attribute_map': {
                    'tenant': 'tenant',
                    'user_tenants': 'user-tenants',
                    'requester_uuid': 'requester-uuid',
                    'user_roles': 'user-roles',
                    'use_openai': 'use_openai',
                    'index_id': 'index_id',
                },
                'location_map': {
                    'tenant': 'query',
                    'user_tenants': 'header',
                    'requester_uuid': 'header',
                    'user_roles': 'header',
                    'user_document_form': 'body',
                    'use_openai': 'query',
                    'index_id': 'query',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    'application/json'
                ],
                'content_type': [
                    'application/json'
                ]
            },
            api_client=api_client
        )
        self.delete_external_document_endpoint = _Endpoint(
            settings={
                'response_type': None,
                'auth': [],
                'endpoint_path': '/external-documents/{document_id}',
                'operation_id': 'delete_external_document',
                'http_method': 'DELETE',
                'servers': None,
            },
            params_map={
                'all': [
                    'document_id',
                    'tenant',
                    'user_tenants',
                    'requester_uuid',
                    'user_roles',
                    'index_id',
                ],
                'required': [
                    'document_id',
                    'tenant',
                    'user_tenants',
                    'requester_uuid',
                    'user_roles',
                ],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'document_id':
                        (str,),
                    'tenant':
                        (str,),
                    'user_tenants':
                        (str,),
                    'requester_uuid':
                        (str,),
                    'user_roles':
                        (str,),
                    'index_id':
                        (str,),
                },
                'attribute_map': {
                    'document_id': 'document_id',
                    'tenant': 'tenant',
                    'user_tenants': 'user-tenants',
                    'requester_uuid': 'requester-uuid',
                    'user_roles': 'user-roles',
                    'index_id': 'index_id',
                },
                'location_map': {
                    'document_id': 'path',
                    'tenant': 'query',
                    'user_tenants': 'header',
                    'requester_uuid': 'header',
                    'user_roles': 'header',
                    'index_id': 'query',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    'application/json'
                ],
                'content_type': [],
            },
            api_client=api_client
        )
        self.filter_external_documents_endpoint = _Endpoint(
            settings={
                'response_type': (PaginatedResponseUserDocumentItem,),
                'auth': [],
                'endpoint_path': '/external-documents',
                'operation_id': 'filter_external_documents',
                'http_method': 'GET',
                'servers': None,
            },
            params_map={
                'all': [
                    'tenant',
                    'user_tenants',
                    'requester_uuid',
                    'user_roles',
                    'deleted',
                    'document_id_in',
                    'uri_hash_in',
                    'crawled_document_id_in',
                    'include_document_status',
                    'include_shared_documents',
                    'index_id',
                    'page',
                    'page_size',
                ],
                'required': [
                    'tenant',
                    'user_tenants',
                    'requester_uuid',
                    'user_roles',
                ],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'tenant':
                        (str,),
                    'user_tenants':
                        (str,),
                    'requester_uuid':
                        (str,),
                    'user_roles':
                        (str,),
                    'deleted':
                        (bool,),
                    'document_id_in':
                        ([str],),
                    'uri_hash_in':
                        ([str],),
                    'crawled_document_id_in':
                        ([str],),
                    'include_document_status':
                        (bool,),
                    'include_shared_documents':
                        (bool,),
                    'index_id':
                        (str,),
                    'page':
                        (int,),
                    'page_size':
                        (int,),
                },
                'attribute_map': {
                    'tenant': 'tenant',
                    'user_tenants': 'user-tenants',
                    'requester_uuid': 'requester-uuid',
                    'user_roles': 'user-roles',
                    'deleted': 'deleted',
                    'document_id_in': 'document_id_in',
                    'uri_hash_in': 'uri_hash_in',
                    'crawled_document_id_in': 'crawled_document_id_in',
                    'include_document_status': 'include_document_status',
                    'include_shared_documents': 'include_shared_documents',
                    'index_id': 'index_id',
                    'page': 'page',
                    'page_size': 'page_size',
                },
                'location_map': {
                    'tenant': 'query',
                    'user_tenants': 'header',
                    'requester_uuid': 'header',
                    'user_roles': 'header',
                    'deleted': 'query',
                    'document_id_in': 'query',
                    'uri_hash_in': 'query',
                    'crawled_document_id_in': 'query',
                    'include_document_status': 'query',
                    'include_shared_documents': 'query',
                    'index_id': 'query',
                    'page': 'query',
                    'page_size': 'query',
                },
                'collection_format_map': {
                    'document_id_in': 'multi',
                    'uri_hash_in': 'multi',
                    'crawled_document_id_in': 'multi',
                }
            },
            headers_map={
                'accept': [
                    'application/json'
                ],
                'content_type': [],
            },
            api_client=api_client
        )
        self.retrieve_external_document_endpoint = _Endpoint(
            settings={
                'response_type': (UserDocumentItem,),
                'auth': [],
                'endpoint_path': '/external-documents/{document_id}',
                'operation_id': 'retrieve_external_document',
                'http_method': 'GET',
                'servers': None,
            },
            params_map={
                'all': [
                    'document_id',
                    'tenant',
                    'user_tenants',
                    'requester_uuid',
                    'user_roles',
                    'include_document_status',
                    'index_id',
                ],
                'required': [
                    'document_id',
                    'tenant',
                    'user_tenants',
                    'requester_uuid',
                    'user_roles',
                ],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'document_id':
                        (str,),
                    'tenant':
                        (str,),
                    'user_tenants':
                        (str,),
                    'requester_uuid':
                        (str,),
                    'user_roles':
                        (str,),
                    'include_document_status':
                        (bool,),
                    'index_id':
                        (str,),
                },
                'attribute_map': {
                    'document_id': 'document_id',
                    'tenant': 'tenant',
                    'user_tenants': 'user-tenants',
                    'requester_uuid': 'requester-uuid',
                    'user_roles': 'user-roles',
                    'include_document_status': 'include_document_status',
                    'index_id': 'index_id',
                },
                'location_map': {
                    'document_id': 'path',
                    'tenant': 'query',
                    'user_tenants': 'header',
                    'requester_uuid': 'header',
                    'user_roles': 'header',
                    'include_document_status': 'query',
                    'index_id': 'query',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    'application/json'
                ],
                'content_type': [],
            },
            api_client=api_client
        )
        self.retrieve_external_document_content_endpoint = _Endpoint(
            settings={
                'response_type': (bool, date, datetime, dict, float, int, list, str, none_type,),
                'auth': [],
                'endpoint_path': '/external-documents/{document_id}/content',
                'operation_id': 'retrieve_external_document_content',
                'http_method': 'GET',
                'servers': None,
            },
            params_map={
                'all': [
                    'document_id',
                    'tenant',
                    'user_tenants',
                    'requester_uuid',
                    'user_roles',
                    'index_id',
                ],
                'required': [
                    'document_id',
                    'tenant',
                    'user_tenants',
                    'requester_uuid',
                    'user_roles',
                ],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'document_id':
                        (str,),
                    'tenant':
                        (str,),
                    'user_tenants':
                        (str,),
                    'requester_uuid':
                        (str,),
                    'user_roles':
                        (str,),
                    'index_id':
                        (str,),
                },
                'attribute_map': {
                    'document_id': 'document_id',
                    'tenant': 'tenant',
                    'user_tenants': 'user-tenants',
                    'requester_uuid': 'requester-uuid',
                    'user_roles': 'user-roles',
                    'index_id': 'index_id',
                },
                'location_map': {
                    'document_id': 'path',
                    'tenant': 'query',
                    'user_tenants': 'header',
                    'requester_uuid': 'header',
                    'user_roles': 'header',
                    'index_id': 'query',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    'application/json'
                ],
                'content_type': [],
            },
            api_client=api_client
        )

    def create_external_document(
        self,
        tenant,
        user_tenants,
        requester_uuid,
        user_roles,
        user_document_form,
        **kwargs
    ):
        """Create External Document  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.create_external_document(tenant, user_tenants, requester_uuid, user_roles, user_document_form, async_req=True)
        >>> result = thread.get()

        Args:
            tenant (str):
            user_tenants (str):
            requester_uuid (str):
            user_roles (str):
            user_document_form (UserDocumentForm):

        Keyword Args:
            use_openai (bool): [optional] if omitted the server will use the default value of True
            index_id (str): [optional]
            _return_http_data_only (bool): response data without head status
                code and headers. Default is True.
            _preload_content (bool): if False, the urllib3.HTTPResponse object
                will be returned without reading/decoding response data.
                Default is True.
            _request_timeout (int/float/tuple): timeout setting for this request. If
                one number provided, it will be total request timeout. It can also
                be a pair (tuple) of (connection, read) timeouts.
                Default is None.
            _check_input_type (bool): specifies if type checking
                should be done one the data sent to the server.
                Default is True.
            _check_return_type (bool): specifies if type checking
                should be done one the data received from the server.
                Default is True.
            _spec_property_naming (bool): True if the variable names in the input data
                are serialized names, as specified in the OpenAPI document.
                False if the variable names in the input data
                are pythonic names, e.g. snake case (default)
            _content_type (str/None): force body content-type.
                Default is None and content-type will be predicted by allowed
                content-types and body.
            _host_index (int/None): specifies the index of the server
                that we want to use.
                Default is read from the configuration.
            async_req (bool): execute request asynchronously

        Returns:
            UserDocumentItem
                If the method is called asynchronously, returns the request
                thread.
        """
        kwargs['async_req'] = kwargs.get(
            'async_req', False
        )
        kwargs['_return_http_data_only'] = kwargs.get(
            '_return_http_data_only', True
        )
        kwargs['_preload_content'] = kwargs.get(
            '_preload_content', True
        )
        kwargs['_request_timeout'] = kwargs.get(
            '_request_timeout', None
        )
        kwargs['_check_input_type'] = kwargs.get(
            '_check_input_type', True
        )
        kwargs['_check_return_type'] = kwargs.get(
            '_check_return_type', True
        )
        kwargs['_spec_property_naming'] = kwargs.get(
            '_spec_property_naming', False
        )
        kwargs['_content_type'] = kwargs.get(
            '_content_type')
        kwargs['_host_index'] = kwargs.get('_host_index')
        kwargs['tenant'] = \
            tenant
        kwargs['user_tenants'] = \
            user_tenants
        kwargs['requester_uuid'] = \
            requester_uuid
        kwargs['user_roles'] = \
            user_roles
        kwargs['user_document_form'] = \
            user_document_form
        return self.create_external_document_endpoint.call_with_http_info(**kwargs)

    def delete_external_document(
        self,
        document_id,
        tenant,
        user_tenants,
        requester_uuid,
        user_roles,
        **kwargs
    ):
        """Delete External Document  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.delete_external_document(document_id, tenant, user_tenants, requester_uuid, user_roles, async_req=True)
        >>> result = thread.get()

        Args:
            document_id (str):
            tenant (str):
            user_tenants (str):
            requester_uuid (str):
            user_roles (str):

        Keyword Args:
            index_id (str): [optional]
            _return_http_data_only (bool): response data without head status
                code and headers. Default is True.
            _preload_content (bool): if False, the urllib3.HTTPResponse object
                will be returned without reading/decoding response data.
                Default is True.
            _request_timeout (int/float/tuple): timeout setting for this request. If
                one number provided, it will be total request timeout. It can also
                be a pair (tuple) of (connection, read) timeouts.
                Default is None.
            _check_input_type (bool): specifies if type checking
                should be done one the data sent to the server.
                Default is True.
            _check_return_type (bool): specifies if type checking
                should be done one the data received from the server.
                Default is True.
            _spec_property_naming (bool): True if the variable names in the input data
                are serialized names, as specified in the OpenAPI document.
                False if the variable names in the input data
                are pythonic names, e.g. snake case (default)
            _content_type (str/None): force body content-type.
                Default is None and content-type will be predicted by allowed
                content-types and body.
            _host_index (int/None): specifies the index of the server
                that we want to use.
                Default is read from the configuration.
            async_req (bool): execute request asynchronously

        Returns:
            None
                If the method is called asynchronously, returns the request
                thread.
        """
        kwargs['async_req'] = kwargs.get(
            'async_req', False
        )
        kwargs['_return_http_data_only'] = kwargs.get(
            '_return_http_data_only', True
        )
        kwargs['_preload_content'] = kwargs.get(
            '_preload_content', True
        )
        kwargs['_request_timeout'] = kwargs.get(
            '_request_timeout', None
        )
        kwargs['_check_input_type'] = kwargs.get(
            '_check_input_type', True
        )
        kwargs['_check_return_type'] = kwargs.get(
            '_check_return_type', True
        )
        kwargs['_spec_property_naming'] = kwargs.get(
            '_spec_property_naming', False
        )
        kwargs['_content_type'] = kwargs.get(
            '_content_type')
        kwargs['_host_index'] = kwargs.get('_host_index')
        kwargs['document_id'] = \
            document_id
        kwargs['tenant'] = \
            tenant
        kwargs['user_tenants'] = \
            user_tenants
        kwargs['requester_uuid'] = \
            requester_uuid
        kwargs['user_roles'] = \
            user_roles
        return self.delete_external_document_endpoint.call_with_http_info(**kwargs)

    def filter_external_documents(
        self,
        tenant,
        user_tenants,
        requester_uuid,
        user_roles,
        **kwargs
    ):
        """Filter External Documents  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.filter_external_documents(tenant, user_tenants, requester_uuid, user_roles, async_req=True)
        >>> result = thread.get()

        Args:
            tenant (str):
            user_tenants (str):
            requester_uuid (str):
            user_roles (str):

        Keyword Args:
            deleted (bool): [optional]
            document_id_in ([str]): [optional]
            uri_hash_in ([str]): [optional]
            crawled_document_id_in ([str]): [optional]
            include_document_status (bool): [optional]
            include_shared_documents (bool): [optional]
            index_id (str): [optional]
            page (int): [optional] if omitted the server will use the default value of 1
            page_size (int): [optional] if omitted the server will use the default value of 100
            _return_http_data_only (bool): response data without head status
                code and headers. Default is True.
            _preload_content (bool): if False, the urllib3.HTTPResponse object
                will be returned without reading/decoding response data.
                Default is True.
            _request_timeout (int/float/tuple): timeout setting for this request. If
                one number provided, it will be total request timeout. It can also
                be a pair (tuple) of (connection, read) timeouts.
                Default is None.
            _check_input_type (bool): specifies if type checking
                should be done one the data sent to the server.
                Default is True.
            _check_return_type (bool): specifies if type checking
                should be done one the data received from the server.
                Default is True.
            _spec_property_naming (bool): True if the variable names in the input data
                are serialized names, as specified in the OpenAPI document.
                False if the variable names in the input data
                are pythonic names, e.g. snake case (default)
            _content_type (str/None): force body content-type.
                Default is None and content-type will be predicted by allowed
                content-types and body.
            _host_index (int/None): specifies the index of the server
                that we want to use.
                Default is read from the configuration.
            async_req (bool): execute request asynchronously

        Returns:
            PaginatedResponseUserDocumentItem
                If the method is called asynchronously, returns the request
                thread.
        """
        kwargs['async_req'] = kwargs.get(
            'async_req', False
        )
        kwargs['_return_http_data_only'] = kwargs.get(
            '_return_http_data_only', True
        )
        kwargs['_preload_content'] = kwargs.get(
            '_preload_content', True
        )
        kwargs['_request_timeout'] = kwargs.get(
            '_request_timeout', None
        )
        kwargs['_check_input_type'] = kwargs.get(
            '_check_input_type', True
        )
        kwargs['_check_return_type'] = kwargs.get(
            '_check_return_type', True
        )
        kwargs['_spec_property_naming'] = kwargs.get(
            '_spec_property_naming', False
        )
        kwargs['_content_type'] = kwargs.get(
            '_content_type')
        kwargs['_host_index'] = kwargs.get('_host_index')
        kwargs['tenant'] = \
            tenant
        kwargs['user_tenants'] = \
            user_tenants
        kwargs['requester_uuid'] = \
            requester_uuid
        kwargs['user_roles'] = \
            user_roles
        return self.filter_external_documents_endpoint.call_with_http_info(**kwargs)

    def retrieve_external_document(
        self,
        document_id,
        tenant,
        user_tenants,
        requester_uuid,
        user_roles,
        **kwargs
    ):
        """Retrieve External Document  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.retrieve_external_document(document_id, tenant, user_tenants, requester_uuid, user_roles, async_req=True)
        >>> result = thread.get()

        Args:
            document_id (str):
            tenant (str):
            user_tenants (str):
            requester_uuid (str):
            user_roles (str):

        Keyword Args:
            include_document_status (bool): [optional]
            index_id (str): [optional]
            _return_http_data_only (bool): response data without head status
                code and headers. Default is True.
            _preload_content (bool): if False, the urllib3.HTTPResponse object
                will be returned without reading/decoding response data.
                Default is True.
            _request_timeout (int/float/tuple): timeout setting for this request. If
                one number provided, it will be total request timeout. It can also
                be a pair (tuple) of (connection, read) timeouts.
                Default is None.
            _check_input_type (bool): specifies if type checking
                should be done one the data sent to the server.
                Default is True.
            _check_return_type (bool): specifies if type checking
                should be done one the data received from the server.
                Default is True.
            _spec_property_naming (bool): True if the variable names in the input data
                are serialized names, as specified in the OpenAPI document.
                False if the variable names in the input data
                are pythonic names, e.g. snake case (default)
            _content_type (str/None): force body content-type.
                Default is None and content-type will be predicted by allowed
                content-types and body.
            _host_index (int/None): specifies the index of the server
                that we want to use.
                Default is read from the configuration.
            async_req (bool): execute request asynchronously

        Returns:
            UserDocumentItem
                If the method is called asynchronously, returns the request
                thread.
        """
        kwargs['async_req'] = kwargs.get(
            'async_req', False
        )
        kwargs['_return_http_data_only'] = kwargs.get(
            '_return_http_data_only', True
        )
        kwargs['_preload_content'] = kwargs.get(
            '_preload_content', True
        )
        kwargs['_request_timeout'] = kwargs.get(
            '_request_timeout', None
        )
        kwargs['_check_input_type'] = kwargs.get(
            '_check_input_type', True
        )
        kwargs['_check_return_type'] = kwargs.get(
            '_check_return_type', True
        )
        kwargs['_spec_property_naming'] = kwargs.get(
            '_spec_property_naming', False
        )
        kwargs['_content_type'] = kwargs.get(
            '_content_type')
        kwargs['_host_index'] = kwargs.get('_host_index')
        kwargs['document_id'] = \
            document_id
        kwargs['tenant'] = \
            tenant
        kwargs['user_tenants'] = \
            user_tenants
        kwargs['requester_uuid'] = \
            requester_uuid
        kwargs['user_roles'] = \
            user_roles
        return self.retrieve_external_document_endpoint.call_with_http_info(**kwargs)

    def retrieve_external_document_content(
        self,
        document_id,
        tenant,
        user_tenants,
        requester_uuid,
        user_roles,
        **kwargs
    ):
        """Retrieve External Document Content  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.retrieve_external_document_content(document_id, tenant, user_tenants, requester_uuid, user_roles, async_req=True)
        >>> result = thread.get()

        Args:
            document_id (str):
            tenant (str):
            user_tenants (str):
            requester_uuid (str):
            user_roles (str):

        Keyword Args:
            index_id (str): [optional]
            _return_http_data_only (bool): response data without head status
                code and headers. Default is True.
            _preload_content (bool): if False, the urllib3.HTTPResponse object
                will be returned without reading/decoding response data.
                Default is True.
            _request_timeout (int/float/tuple): timeout setting for this request. If
                one number provided, it will be total request timeout. It can also
                be a pair (tuple) of (connection, read) timeouts.
                Default is None.
            _check_input_type (bool): specifies if type checking
                should be done one the data sent to the server.
                Default is True.
            _check_return_type (bool): specifies if type checking
                should be done one the data received from the server.
                Default is True.
            _spec_property_naming (bool): True if the variable names in the input data
                are serialized names, as specified in the OpenAPI document.
                False if the variable names in the input data
                are pythonic names, e.g. snake case (default)
            _content_type (str/None): force body content-type.
                Default is None and content-type will be predicted by allowed
                content-types and body.
            _host_index (int/None): specifies the index of the server
                that we want to use.
                Default is read from the configuration.
            async_req (bool): execute request asynchronously

        Returns:
            bool, date, datetime, dict, float, int, list, str, none_type
                If the method is called asynchronously, returns the request
                thread.
        """
        kwargs['async_req'] = kwargs.get(
            'async_req', False
        )
        kwargs['_return_http_data_only'] = kwargs.get(
            '_return_http_data_only', True
        )
        kwargs['_preload_content'] = kwargs.get(
            '_preload_content', True
        )
        kwargs['_request_timeout'] = kwargs.get(
            '_request_timeout', None
        )
        kwargs['_check_input_type'] = kwargs.get(
            '_check_input_type', True
        )
        kwargs['_check_return_type'] = kwargs.get(
            '_check_return_type', True
        )
        kwargs['_spec_property_naming'] = kwargs.get(
            '_spec_property_naming', False
        )
        kwargs['_content_type'] = kwargs.get(
            '_content_type')
        kwargs['_host_index'] = kwargs.get('_host_index')
        kwargs['document_id'] = \
            document_id
        kwargs['tenant'] = \
            tenant
        kwargs['user_tenants'] = \
            user_tenants
        kwargs['requester_uuid'] = \
            requester_uuid
        kwargs['user_roles'] = \
            user_roles
        return self.retrieve_external_document_content_endpoint.call_with_http_info(**kwargs)

