# flake8: noqa

"""
    authentication-service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: latest
    Generated by: https://openapi-generator.tech
"""


__version__ = "2.6.11"

# import ApiClient
from zav.authentication_service.api_client import ApiClient

# import Configuration
from zav.authentication_service.configuration import Configuration

# import exceptions
from zav.authentication_service.exceptions import OpenApiException
from zav.authentication_service.exceptions import ApiAttributeError
from zav.authentication_service.exceptions import ApiTypeError
from zav.authentication_service.exceptions import ApiValueError
from zav.authentication_service.exceptions import ApiKeyError
from zav.authentication_service.exceptions import ApiException
