"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

from zav.chat_service.api_client import ApiClient, Endpoint as _Endpoint
from zav.chat_service.model_utils import (  # noqa: F401
    check_allowed_values,
    check_validations,
    date,
    datetime,
    file_type,
    none_type,
    validate_and_convert_types
)
from zav.chat_service.model.agent_task_item import AgentTaskItem
from zav.chat_service.model.http_validation_error import HTTPValidationError
from zav.chat_service.model.paginated_response_scheduled_agent_task_item import PaginatedResponseScheduledAgentTaskItem
from zav.chat_service.model.scheduled_agent_task_form import ScheduledAgentTaskForm
from zav.chat_service.model.scheduled_agent_task_item import ScheduledAgentTaskItem
from zav.chat_service.model.scheduled_agent_task_patch import ScheduledAgentTaskPatch


class ScheduledAgentTasksApi(object):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client
        self.create_scheduled_agent_task_endpoint = _Endpoint(
            settings={
                'response_type': (ScheduledAgentTaskItem,),
                'auth': [],
                'endpoint_path': '/scheduled-agent-tasks',
                'operation_id': 'create_scheduled_agent_task',
                'http_method': 'POST',
                'servers': None,
            },
            params_map={
                'all': [
                    'tenant',
                    'user_tenants',
                    'requester_uuid',
                    'user_roles',
                    'scheduled_agent_task_form',
                    'index_id',
                ],
                'required': [
                    'tenant',
                    'user_tenants',
                    'requester_uuid',
                    'user_roles',
                    'scheduled_agent_task_form',
                ],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'tenant':
                        (str,),
                    'user_tenants':
                        (str,),
                    'requester_uuid':
                        (str,),
                    'user_roles':
                        (str,),
                    'scheduled_agent_task_form':
                        (ScheduledAgentTaskForm,),
                    'index_id':
                        (str,),
                },
                'attribute_map': {
                    'tenant': 'tenant',
                    'user_tenants': 'user-tenants',
                    'requester_uuid': 'requester-uuid',
                    'user_roles': 'user-roles',
                    'index_id': 'index_id',
                },
                'location_map': {
                    'tenant': 'query',
                    'user_tenants': 'header',
                    'requester_uuid': 'header',
                    'user_roles': 'header',
                    'scheduled_agent_task_form': 'body',
                    'index_id': 'query',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    'application/json'
                ],
                'content_type': [
                    'application/json'
                ]
            },
            api_client=api_client
        )
        self.delete_scheduled_agent_task_endpoint = _Endpoint(
            settings={
                'response_type': None,
                'auth': [],
                'endpoint_path': '/scheduled-agent-tasks/{agent_id}',
                'operation_id': 'delete_scheduled_agent_task',
                'http_method': 'DELETE',
                'servers': None,
            },
            params_map={
                'all': [
                    'agent_id',
                    'tenant',
                    'user_tenants',
                    'requester_uuid',
                ],
                'required': [
                    'agent_id',
                    'tenant',
                    'user_tenants',
                    'requester_uuid',
                ],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'agent_id':
                        (str,),
                    'tenant':
                        (str,),
                    'user_tenants':
                        (str,),
                    'requester_uuid':
                        (str,),
                },
                'attribute_map': {
                    'agent_id': 'agent_id',
                    'tenant': 'tenant',
                    'user_tenants': 'user-tenants',
                    'requester_uuid': 'requester-uuid',
                },
                'location_map': {
                    'agent_id': 'path',
                    'tenant': 'query',
                    'user_tenants': 'header',
                    'requester_uuid': 'header',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    'application/json'
                ],
                'content_type': [],
            },
            api_client=api_client
        )
        self.filter_scheduled_agent_task_endpoint = _Endpoint(
            settings={
                'response_type': (PaginatedResponseScheduledAgentTaskItem,),
                'auth': [],
                'endpoint_path': '/scheduled-agent-tasks',
                'operation_id': 'filter_scheduled_agent_task',
                'http_method': 'GET',
                'servers': None,
            },
            params_map={
                'all': [
                    'tenant',
                    'user_tenants',
                    'requester_uuid',
                    'is_active',
                    'agent_id_in',
                    'page',
                    'page_size',
                ],
                'required': [
                    'tenant',
                    'user_tenants',
                    'requester_uuid',
                ],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'tenant':
                        (str,),
                    'user_tenants':
                        (str,),
                    'requester_uuid':
                        (str,),
                    'is_active':
                        (bool,),
                    'agent_id_in':
                        ([str],),
                    'page':
                        (int,),
                    'page_size':
                        (int,),
                },
                'attribute_map': {
                    'tenant': 'tenant',
                    'user_tenants': 'user-tenants',
                    'requester_uuid': 'requester-uuid',
                    'is_active': 'is_active',
                    'agent_id_in': 'agent_id_in',
                    'page': 'page',
                    'page_size': 'page_size',
                },
                'location_map': {
                    'tenant': 'query',
                    'user_tenants': 'header',
                    'requester_uuid': 'header',
                    'is_active': 'query',
                    'agent_id_in': 'query',
                    'page': 'query',
                    'page_size': 'query',
                },
                'collection_format_map': {
                    'agent_id_in': 'multi',
                }
            },
            headers_map={
                'accept': [
                    'application/json'
                ],
                'content_type': [],
            },
            api_client=api_client
        )
        self.retrieve_latest_task_for_scheduled_agent_task_endpoint = _Endpoint(
            settings={
                'response_type': (AgentTaskItem,),
                'auth': [],
                'endpoint_path': '/scheduled-agent-tasks/{agent_id}/latest-task',
                'operation_id': 'retrieve_latest_task_for_scheduled_agent_task',
                'http_method': 'GET',
                'servers': None,
            },
            params_map={
                'all': [
                    'agent_id',
                    'tenant',
                    'user_tenants',
                    'requester_uuid',
                ],
                'required': [
                    'agent_id',
                    'tenant',
                    'user_tenants',
                    'requester_uuid',
                ],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'agent_id':
                        (str,),
                    'tenant':
                        (str,),
                    'user_tenants':
                        (str,),
                    'requester_uuid':
                        (str,),
                },
                'attribute_map': {
                    'agent_id': 'agent_id',
                    'tenant': 'tenant',
                    'user_tenants': 'user-tenants',
                    'requester_uuid': 'requester-uuid',
                },
                'location_map': {
                    'agent_id': 'path',
                    'tenant': 'query',
                    'user_tenants': 'header',
                    'requester_uuid': 'header',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    'application/json'
                ],
                'content_type': [],
            },
            api_client=api_client
        )
        self.retrieve_scheduled_agent_task_endpoint = _Endpoint(
            settings={
                'response_type': (ScheduledAgentTaskItem,),
                'auth': [],
                'endpoint_path': '/scheduled-agent-tasks/{agent_id}',
                'operation_id': 'retrieve_scheduled_agent_task',
                'http_method': 'GET',
                'servers': None,
            },
            params_map={
                'all': [
                    'agent_id',
                    'tenant',
                    'user_tenants',
                    'requester_uuid',
                ],
                'required': [
                    'agent_id',
                    'tenant',
                    'user_tenants',
                    'requester_uuid',
                ],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'agent_id':
                        (str,),
                    'tenant':
                        (str,),
                    'user_tenants':
                        (str,),
                    'requester_uuid':
                        (str,),
                },
                'attribute_map': {
                    'agent_id': 'agent_id',
                    'tenant': 'tenant',
                    'user_tenants': 'user-tenants',
                    'requester_uuid': 'requester-uuid',
                },
                'location_map': {
                    'agent_id': 'path',
                    'tenant': 'query',
                    'user_tenants': 'header',
                    'requester_uuid': 'header',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    'application/json'
                ],
                'content_type': [],
            },
            api_client=api_client
        )
        self.update_scheduled_agent_task_endpoint = _Endpoint(
            settings={
                'response_type': None,
                'auth': [],
                'endpoint_path': '/scheduled-agent-tasks/{agent_id}',
                'operation_id': 'update_scheduled_agent_task',
                'http_method': 'PATCH',
                'servers': None,
            },
            params_map={
                'all': [
                    'agent_id',
                    'tenant',
                    'user_tenants',
                    'requester_uuid',
                    'user_roles',
                    'scheduled_agent_task_patch',
                ],
                'required': [
                    'agent_id',
                    'tenant',
                    'user_tenants',
                    'requester_uuid',
                    'user_roles',
                    'scheduled_agent_task_patch',
                ],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'agent_id':
                        (str,),
                    'tenant':
                        (str,),
                    'user_tenants':
                        (str,),
                    'requester_uuid':
                        (str,),
                    'user_roles':
                        (str,),
                    'scheduled_agent_task_patch':
                        (ScheduledAgentTaskPatch,),
                },
                'attribute_map': {
                    'agent_id': 'agent_id',
                    'tenant': 'tenant',
                    'user_tenants': 'user-tenants',
                    'requester_uuid': 'requester-uuid',
                    'user_roles': 'user-roles',
                },
                'location_map': {
                    'agent_id': 'path',
                    'tenant': 'query',
                    'user_tenants': 'header',
                    'requester_uuid': 'header',
                    'user_roles': 'header',
                    'scheduled_agent_task_patch': 'body',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    'application/json'
                ],
                'content_type': [
                    'application/json'
                ]
            },
            api_client=api_client
        )

    def create_scheduled_agent_task(
        self,
        tenant,
        user_tenants,
        requester_uuid,
        user_roles,
        scheduled_agent_task_form,
        **kwargs
    ):
        """Create Scheduled Agent Task  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.create_scheduled_agent_task(tenant, user_tenants, requester_uuid, user_roles, scheduled_agent_task_form, async_req=True)
        >>> result = thread.get()

        Args:
            tenant (str):
            user_tenants (str):
            requester_uuid (str):
            user_roles (str):
            scheduled_agent_task_form (ScheduledAgentTaskForm):

        Keyword Args:
            index_id (str): [optional]
            _return_http_data_only (bool): response data without head status
                code and headers. Default is True.
            _preload_content (bool): if False, the urllib3.HTTPResponse object
                will be returned without reading/decoding response data.
                Default is True.
            _request_timeout (int/float/tuple): timeout setting for this request. If
                one number provided, it will be total request timeout. It can also
                be a pair (tuple) of (connection, read) timeouts.
                Default is None.
            _check_input_type (bool): specifies if type checking
                should be done one the data sent to the server.
                Default is True.
            _check_return_type (bool): specifies if type checking
                should be done one the data received from the server.
                Default is True.
            _spec_property_naming (bool): True if the variable names in the input data
                are serialized names, as specified in the OpenAPI document.
                False if the variable names in the input data
                are pythonic names, e.g. snake case (default)
            _content_type (str/None): force body content-type.
                Default is None and content-type will be predicted by allowed
                content-types and body.
            _host_index (int/None): specifies the index of the server
                that we want to use.
                Default is read from the configuration.
            async_req (bool): execute request asynchronously

        Returns:
            ScheduledAgentTaskItem
                If the method is called asynchronously, returns the request
                thread.
        """
        kwargs['async_req'] = kwargs.get(
            'async_req', False
        )
        kwargs['_return_http_data_only'] = kwargs.get(
            '_return_http_data_only', True
        )
        kwargs['_preload_content'] = kwargs.get(
            '_preload_content', True
        )
        kwargs['_request_timeout'] = kwargs.get(
            '_request_timeout', None
        )
        kwargs['_check_input_type'] = kwargs.get(
            '_check_input_type', True
        )
        kwargs['_check_return_type'] = kwargs.get(
            '_check_return_type', True
        )
        kwargs['_spec_property_naming'] = kwargs.get(
            '_spec_property_naming', False
        )
        kwargs['_content_type'] = kwargs.get(
            '_content_type')
        kwargs['_host_index'] = kwargs.get('_host_index')
        kwargs['tenant'] = \
            tenant
        kwargs['user_tenants'] = \
            user_tenants
        kwargs['requester_uuid'] = \
            requester_uuid
        kwargs['user_roles'] = \
            user_roles
        kwargs['scheduled_agent_task_form'] = \
            scheduled_agent_task_form
        return self.create_scheduled_agent_task_endpoint.call_with_http_info(**kwargs)

    def delete_scheduled_agent_task(
        self,
        agent_id,
        tenant,
        user_tenants,
        requester_uuid,
        **kwargs
    ):
        """Delete Scheduled Agent Task  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.delete_scheduled_agent_task(agent_id, tenant, user_tenants, requester_uuid, async_req=True)
        >>> result = thread.get()

        Args:
            agent_id (str):
            tenant (str):
            user_tenants (str):
            requester_uuid (str):

        Keyword Args:
            _return_http_data_only (bool): response data without head status
                code and headers. Default is True.
            _preload_content (bool): if False, the urllib3.HTTPResponse object
                will be returned without reading/decoding response data.
                Default is True.
            _request_timeout (int/float/tuple): timeout setting for this request. If
                one number provided, it will be total request timeout. It can also
                be a pair (tuple) of (connection, read) timeouts.
                Default is None.
            _check_input_type (bool): specifies if type checking
                should be done one the data sent to the server.
                Default is True.
            _check_return_type (bool): specifies if type checking
                should be done one the data received from the server.
                Default is True.
            _spec_property_naming (bool): True if the variable names in the input data
                are serialized names, as specified in the OpenAPI document.
                False if the variable names in the input data
                are pythonic names, e.g. snake case (default)
            _content_type (str/None): force body content-type.
                Default is None and content-type will be predicted by allowed
                content-types and body.
            _host_index (int/None): specifies the index of the server
                that we want to use.
                Default is read from the configuration.
            async_req (bool): execute request asynchronously

        Returns:
            None
                If the method is called asynchronously, returns the request
                thread.
        """
        kwargs['async_req'] = kwargs.get(
            'async_req', False
        )
        kwargs['_return_http_data_only'] = kwargs.get(
            '_return_http_data_only', True
        )
        kwargs['_preload_content'] = kwargs.get(
            '_preload_content', True
        )
        kwargs['_request_timeout'] = kwargs.get(
            '_request_timeout', None
        )
        kwargs['_check_input_type'] = kwargs.get(
            '_check_input_type', True
        )
        kwargs['_check_return_type'] = kwargs.get(
            '_check_return_type', True
        )
        kwargs['_spec_property_naming'] = kwargs.get(
            '_spec_property_naming', False
        )
        kwargs['_content_type'] = kwargs.get(
            '_content_type')
        kwargs['_host_index'] = kwargs.get('_host_index')
        kwargs['agent_id'] = \
            agent_id
        kwargs['tenant'] = \
            tenant
        kwargs['user_tenants'] = \
            user_tenants
        kwargs['requester_uuid'] = \
            requester_uuid
        return self.delete_scheduled_agent_task_endpoint.call_with_http_info(**kwargs)

    def filter_scheduled_agent_task(
        self,
        tenant,
        user_tenants,
        requester_uuid,
        **kwargs
    ):
        """Filter Scheduled Agent Task  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.filter_scheduled_agent_task(tenant, user_tenants, requester_uuid, async_req=True)
        >>> result = thread.get()

        Args:
            tenant (str):
            user_tenants (str):
            requester_uuid (str):

        Keyword Args:
            is_active (bool): [optional]
            agent_id_in ([str]): [optional]
            page (int): [optional] if omitted the server will use the default value of 1
            page_size (int): [optional] if omitted the server will use the default value of 100
            _return_http_data_only (bool): response data without head status
                code and headers. Default is True.
            _preload_content (bool): if False, the urllib3.HTTPResponse object
                will be returned without reading/decoding response data.
                Default is True.
            _request_timeout (int/float/tuple): timeout setting for this request. If
                one number provided, it will be total request timeout. It can also
                be a pair (tuple) of (connection, read) timeouts.
                Default is None.
            _check_input_type (bool): specifies if type checking
                should be done one the data sent to the server.
                Default is True.
            _check_return_type (bool): specifies if type checking
                should be done one the data received from the server.
                Default is True.
            _spec_property_naming (bool): True if the variable names in the input data
                are serialized names, as specified in the OpenAPI document.
                False if the variable names in the input data
                are pythonic names, e.g. snake case (default)
            _content_type (str/None): force body content-type.
                Default is None and content-type will be predicted by allowed
                content-types and body.
            _host_index (int/None): specifies the index of the server
                that we want to use.
                Default is read from the configuration.
            async_req (bool): execute request asynchronously

        Returns:
            PaginatedResponseScheduledAgentTaskItem
                If the method is called asynchronously, returns the request
                thread.
        """
        kwargs['async_req'] = kwargs.get(
            'async_req', False
        )
        kwargs['_return_http_data_only'] = kwargs.get(
            '_return_http_data_only', True
        )
        kwargs['_preload_content'] = kwargs.get(
            '_preload_content', True
        )
        kwargs['_request_timeout'] = kwargs.get(
            '_request_timeout', None
        )
        kwargs['_check_input_type'] = kwargs.get(
            '_check_input_type', True
        )
        kwargs['_check_return_type'] = kwargs.get(
            '_check_return_type', True
        )
        kwargs['_spec_property_naming'] = kwargs.get(
            '_spec_property_naming', False
        )
        kwargs['_content_type'] = kwargs.get(
            '_content_type')
        kwargs['_host_index'] = kwargs.get('_host_index')
        kwargs['tenant'] = \
            tenant
        kwargs['user_tenants'] = \
            user_tenants
        kwargs['requester_uuid'] = \
            requester_uuid
        return self.filter_scheduled_agent_task_endpoint.call_with_http_info(**kwargs)

    def retrieve_latest_task_for_scheduled_agent_task(
        self,
        agent_id,
        tenant,
        user_tenants,
        requester_uuid,
        **kwargs
    ):
        """Retrieve Latest Task For Scheduled Agent Task  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.retrieve_latest_task_for_scheduled_agent_task(agent_id, tenant, user_tenants, requester_uuid, async_req=True)
        >>> result = thread.get()

        Args:
            agent_id (str):
            tenant (str):
            user_tenants (str):
            requester_uuid (str):

        Keyword Args:
            _return_http_data_only (bool): response data without head status
                code and headers. Default is True.
            _preload_content (bool): if False, the urllib3.HTTPResponse object
                will be returned without reading/decoding response data.
                Default is True.
            _request_timeout (int/float/tuple): timeout setting for this request. If
                one number provided, it will be total request timeout. It can also
                be a pair (tuple) of (connection, read) timeouts.
                Default is None.
            _check_input_type (bool): specifies if type checking
                should be done one the data sent to the server.
                Default is True.
            _check_return_type (bool): specifies if type checking
                should be done one the data received from the server.
                Default is True.
            _spec_property_naming (bool): True if the variable names in the input data
                are serialized names, as specified in the OpenAPI document.
                False if the variable names in the input data
                are pythonic names, e.g. snake case (default)
            _content_type (str/None): force body content-type.
                Default is None and content-type will be predicted by allowed
                content-types and body.
            _host_index (int/None): specifies the index of the server
                that we want to use.
                Default is read from the configuration.
            async_req (bool): execute request asynchronously

        Returns:
            AgentTaskItem
                If the method is called asynchronously, returns the request
                thread.
        """
        kwargs['async_req'] = kwargs.get(
            'async_req', False
        )
        kwargs['_return_http_data_only'] = kwargs.get(
            '_return_http_data_only', True
        )
        kwargs['_preload_content'] = kwargs.get(
            '_preload_content', True
        )
        kwargs['_request_timeout'] = kwargs.get(
            '_request_timeout', None
        )
        kwargs['_check_input_type'] = kwargs.get(
            '_check_input_type', True
        )
        kwargs['_check_return_type'] = kwargs.get(
            '_check_return_type', True
        )
        kwargs['_spec_property_naming'] = kwargs.get(
            '_spec_property_naming', False
        )
        kwargs['_content_type'] = kwargs.get(
            '_content_type')
        kwargs['_host_index'] = kwargs.get('_host_index')
        kwargs['agent_id'] = \
            agent_id
        kwargs['tenant'] = \
            tenant
        kwargs['user_tenants'] = \
            user_tenants
        kwargs['requester_uuid'] = \
            requester_uuid
        return self.retrieve_latest_task_for_scheduled_agent_task_endpoint.call_with_http_info(**kwargs)

    def retrieve_scheduled_agent_task(
        self,
        agent_id,
        tenant,
        user_tenants,
        requester_uuid,
        **kwargs
    ):
        """Retrieve Scheduled Agent Task  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.retrieve_scheduled_agent_task(agent_id, tenant, user_tenants, requester_uuid, async_req=True)
        >>> result = thread.get()

        Args:
            agent_id (str):
            tenant (str):
            user_tenants (str):
            requester_uuid (str):

        Keyword Args:
            _return_http_data_only (bool): response data without head status
                code and headers. Default is True.
            _preload_content (bool): if False, the urllib3.HTTPResponse object
                will be returned without reading/decoding response data.
                Default is True.
            _request_timeout (int/float/tuple): timeout setting for this request. If
                one number provided, it will be total request timeout. It can also
                be a pair (tuple) of (connection, read) timeouts.
                Default is None.
            _check_input_type (bool): specifies if type checking
                should be done one the data sent to the server.
                Default is True.
            _check_return_type (bool): specifies if type checking
                should be done one the data received from the server.
                Default is True.
            _spec_property_naming (bool): True if the variable names in the input data
                are serialized names, as specified in the OpenAPI document.
                False if the variable names in the input data
                are pythonic names, e.g. snake case (default)
            _content_type (str/None): force body content-type.
                Default is None and content-type will be predicted by allowed
                content-types and body.
            _host_index (int/None): specifies the index of the server
                that we want to use.
                Default is read from the configuration.
            async_req (bool): execute request asynchronously

        Returns:
            ScheduledAgentTaskItem
                If the method is called asynchronously, returns the request
                thread.
        """
        kwargs['async_req'] = kwargs.get(
            'async_req', False
        )
        kwargs['_return_http_data_only'] = kwargs.get(
            '_return_http_data_only', True
        )
        kwargs['_preload_content'] = kwargs.get(
            '_preload_content', True
        )
        kwargs['_request_timeout'] = kwargs.get(
            '_request_timeout', None
        )
        kwargs['_check_input_type'] = kwargs.get(
            '_check_input_type', True
        )
        kwargs['_check_return_type'] = kwargs.get(
            '_check_return_type', True
        )
        kwargs['_spec_property_naming'] = kwargs.get(
            '_spec_property_naming', False
        )
        kwargs['_content_type'] = kwargs.get(
            '_content_type')
        kwargs['_host_index'] = kwargs.get('_host_index')
        kwargs['agent_id'] = \
            agent_id
        kwargs['tenant'] = \
            tenant
        kwargs['user_tenants'] = \
            user_tenants
        kwargs['requester_uuid'] = \
            requester_uuid
        return self.retrieve_scheduled_agent_task_endpoint.call_with_http_info(**kwargs)

    def update_scheduled_agent_task(
        self,
        agent_id,
        tenant,
        user_tenants,
        requester_uuid,
        user_roles,
        scheduled_agent_task_patch,
        **kwargs
    ):
        """Update Scheduled Agent Task  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.update_scheduled_agent_task(agent_id, tenant, user_tenants, requester_uuid, user_roles, scheduled_agent_task_patch, async_req=True)
        >>> result = thread.get()

        Args:
            agent_id (str):
            tenant (str):
            user_tenants (str):
            requester_uuid (str):
            user_roles (str):
            scheduled_agent_task_patch (ScheduledAgentTaskPatch):

        Keyword Args:
            _return_http_data_only (bool): response data without head status
                code and headers. Default is True.
            _preload_content (bool): if False, the urllib3.HTTPResponse object
                will be returned without reading/decoding response data.
                Default is True.
            _request_timeout (int/float/tuple): timeout setting for this request. If
                one number provided, it will be total request timeout. It can also
                be a pair (tuple) of (connection, read) timeouts.
                Default is None.
            _check_input_type (bool): specifies if type checking
                should be done one the data sent to the server.
                Default is True.
            _check_return_type (bool): specifies if type checking
                should be done one the data received from the server.
                Default is True.
            _spec_property_naming (bool): True if the variable names in the input data
                are serialized names, as specified in the OpenAPI document.
                False if the variable names in the input data
                are pythonic names, e.g. snake case (default)
            _content_type (str/None): force body content-type.
                Default is None and content-type will be predicted by allowed
                content-types and body.
            _host_index (int/None): specifies the index of the server
                that we want to use.
                Default is read from the configuration.
            async_req (bool): execute request asynchronously

        Returns:
            None
                If the method is called asynchronously, returns the request
                thread.
        """
        kwargs['async_req'] = kwargs.get(
            'async_req', False
        )
        kwargs['_return_http_data_only'] = kwargs.get(
            '_return_http_data_only', True
        )
        kwargs['_preload_content'] = kwargs.get(
            '_preload_content', True
        )
        kwargs['_request_timeout'] = kwargs.get(
            '_request_timeout', None
        )
        kwargs['_check_input_type'] = kwargs.get(
            '_check_input_type', True
        )
        kwargs['_check_return_type'] = kwargs.get(
            '_check_return_type', True
        )
        kwargs['_spec_property_naming'] = kwargs.get(
            '_spec_property_naming', False
        )
        kwargs['_content_type'] = kwargs.get(
            '_content_type')
        kwargs['_host_index'] = kwargs.get('_host_index')
        kwargs['agent_id'] = \
            agent_id
        kwargs['tenant'] = \
            tenant
        kwargs['user_tenants'] = \
            user_tenants
        kwargs['requester_uuid'] = \
            requester_uuid
        kwargs['user_roles'] = \
            user_roles
        kwargs['scheduled_agent_task_patch'] = \
            scheduled_agent_task_patch
        return self.update_scheduled_agent_task_endpoint.call_with_http_info(**kwargs)

